### ISSUE TITLE
Use Apache Tika server

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario-toolbox#14]
As far as I can see in the Apache Tika documentation there is a server app which other processes can send request to process files. I think we should allow the user to use this option within the toolbox. We can have a configuration to allow the user define if it prefers use the jar file directly or send the file to  the Apache Tika server. 

To make easier the development process we can add simple command to start the server locally for testing purposes. 

Furthermore, this will simplify the deployment of the text processing pileline.

**Comment by aassumpcao** [comment]
tá na boca do gol, vou subir a PR logo menos

**Comment by jaswdr** [comment]
@aassumpcao why this was closed without a PR?

**Comment by aassumpcao** [comment]
@jaswdr, we've eventually decided to drop this.
