### ISSUE TITLE
Make tests: Nothing to be done for 'tests'

### ISSUE THREAD

**Issue by guilhermelowa** [okfn-brasil/querido-diario-toolbox#32]
According to README, I run the command `make tests` and received the following error:

`make: Nothing to be done for 'tests'.`

On Makefile you have:

`.PHONY: test \n
test:
`

So running `make test` did run the tests, although in the end I received:

`
FAILED (errors=1, expected failures=3) \n
make: *** [Makefile:42: test] Error 1
`

If you want I can open a PR changing the Makefile to "tests" instead.

**Comment by giuliocc** [comment]
Hi @guilhermelowa! Please do if you are able to :)

**Comment by giuliocc** [comment]
Valeu por apontar isso @guilhermelowa !

Recentemente corrigido por b4a9995.

---

### English

Thanks for pointing that out @guilhermelowa !

Recently fixed by b4a9995.
