### ISSUE TITLE
Add functions to extract cnpjs from texts 

### ISSUE THREAD

**Issue by lubianat** [okfn-brasil/querido-diario-toolbox#7]
Hello, 

We made a couple of functions to extract and validate CNPJs from texts. Before making a PR, perhaps we can decide on some details?

In the current implementations, it requires a couple extra dependencies, some of which could likely be removed.

You can find the [code here](https://github.com/lubianat/transparencia_na_pandemia/blob/master/misc/cpf_extractor/cnpj_extractor/cnpj_extractor/cnpj_extractor.py) and the [unit tests here](https://github.com/lubianat/transparencia_na_pandemia/blob/master/misc/cpf_extractor/cnpj_extractor/tests/cnpj_extractor_unittest.py). 

Any thoughts on what we can do before making a PR to add that to this framework?

**Comment by jvanz** [comment]
Awesome! I'm glad to see your issue about this. I just enter in the repo to add this exact same issue. xD

About the code. I would like to avoid pandas dependency now. I think it will be necessary in the future but not now. I believe we can add the low level functions which receives a string/iterator/list of strings and returns the CNPJs found. As well as the validation function. 

There is not need to add an integration with pandas now. We still discussing how we will integrate the lib code with other frameworks and libs (pandas or any other). But this is another level of abstraction on top of these low level functions. 

Does is make sense for you? Have I answer your question? Please, feel free to ask here of any other communication channel.

**Comment by aassumpcao** [comment]
@lubianat this is great, thank you! I have just pushed a PR for review by @jvanz and @sergiomario. I would suggest you fork  the repo/update your fork after the review.

Along the lines of @jvanz's comment, I would suggest creating a py file under process/etl where you write the low level functions to extract cnpj and cpf. You can then write the wrapper inside the Gazette class in the parent folder and add the unit tests on the Gazette method. Does that make sense? Let me know and we'll chat! Tks!

**Comment by aassumpcao** [comment]
@lubianat I've used your work and that of someone else I found online for the `scan_cnpj()` and `scan_cpf()` methods. Would you mind taking a look and confirming it all makes sense? I'd like to attribute credit to you in the script as well, just let me know how to go about it. tks!

**Comment by aassumpcao** [comment]
done!
